const questions = [
  "I enjoy working with tools, machines, or technology to build or fix things.",
  "I prefer practical, hands-on activities over theoretical ones.",
  "I like outdoor or physical activities where I can see visible results.",
  "I enjoy solving complex problems or puzzles that require deep thinking.",
  "I like analyzing data, conducting experiments, or researching new ideas.",
  "I prefer exploring “why” things happen rather than just “how.”",
  "I like expressing myself through creative work such as art, music, or writing.",
  "I enjoy thinking outside the box and creating something original.",
  "I prefer flexible environments where I can innovate freely.",
  "I enjoy helping others learn, grow, or solve personal problems.",
  "I feel energized when working in groups or supporting people.",
  "I like activities that involve teaching, counseling, or community service.",
  "I enjoy persuading, motivating, or influencing people.",
  "I like taking charge in group projects and leading others.",
  "I am comfortable taking risks to achieve business or career success.",
  "I enjoy organizing information, records, or data systematically.",
  "I prefer working in structured environments with clear rules and processes.",
  "I like tasks that require attention to detail and accuracy.",
  "I can identify solutions quickly when faced with difficult challenges.",
  "I carefully evaluate different options before making a decision.",
  "I can clearly express my ideas and understand others effectively.",
  "I work well with others and contribute effectively to group goals.",
  "I often come up with original ideas or innovative solutions.",
  "I can manage my time well and complete tasks within deadlines.",
]

export { questions }
